---
# Per environment values which override defaults in hmpps-challenge-support-intervention-plan-ui/values.yaml

generic-service:
  ingress:
    host: csip-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true

  env:
    INGRESS_URL: "https://csip-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    CSIP_API_URL: "https://csip-api-preprod.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk" # used by hmpps-connect-dps-components module
    COMMON_COMPONENTS_ENABLED: true
    DPS_HOME_PAGE_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    PRISONER_PROFILE_URL: "https://prisoner-preprod.digital.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION # Phase banner tag label
    AUDIT_ENABLED: "false"
    SENTRY_ENVIRONMENT: PRE-PRODUCTION
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "hmpps-challenge-support-intervention-plan-ui"
    FEATURE_CHANGE_FLOWS: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-non-prod
  businessHoursOnly: true
